### ISSUE TITLE
Clicks on TX confirmation notifications lead to etherscan.io

### ISSUE THREAD

**Issue by erikrijn** [ubiq/sparrow-extension-legacy#2]
Clicks on TX confirmation notifications lead to etherscan.io
![image](https://user-images.githubusercontent.com/14080280/92567065-6fdfe780-f27d-11ea-90f7-a3bbaff5181f.png)

Handled by @metamask/etherscan-link
https://github.com/ubiq/sparrow-extension/blob/1db3b7f939a29a86aa1d84b48d118dd98203f0bc/app/scripts/platforms/extension.js#L2

**Comment by jyap808** [comment]
Good find. 

Need to fork https://github.com/MetaMask/etherscan-link

Cc: @iquidus

**Comment by jyap808** [comment]
References:
```
package.json:    "@metamask/etherscan-link": "^1.1.0",
yarn.lock:"@metamask/etherscan-link@^1.1.0":
app/scripts/platforms/extension.js:import { createExplorerLink as explorerLink } from '@metamask/etherscan-link'
ui/app/pages/asset/components/token-asset.js:import { createAccountLink } from '@metamask/etherscan-link'
```

**Comment by jyap808** [comment]
Looks like we ported this previously. I'll update it: https://github.com/ubiq/ubiqscan-link
