### ISSUE TITLE
Sparrow opens multiple windows for BatchRequest.execute()

### ISSUE THREAD

**Issue by jpatel888** [ubiq/sparrow-extension-legacy#4]
**Describe the bug**
When executing batch transactions, Sparrow (along with MetaMask) opens multiple identical approval windows on web3.BatchRequest.execute(), all to approve all of them.

Because an app being able to open as many windows as it wants can be considered a risk, and because all windows opened are identical anyway, only one window should be opened.

Ex.
<img width="324" alt="Sparrow Error" src="https://user-images.githubusercontent.com/14117763/105658058-bb450c00-5e93-11eb-85c1-029a68d18009.png">

**Steps to reproduce**

1. Go to https://codesandbox.io/s/004m2
2. Connect your Sparrow wallet
3. Wait 3 seconds after the connect window closes
4. Notice that two identical approval windows have opened for the two transaction batch

**Expected behavior**
Only one window to confirm/reject all the transactions needs to be opened.

**Browser details (please complete the following information):**
 - OS: macOS Mojave 10.14.4
 - Browser: Chrome 87.0.4280.141 (64 bit), Brave 1.18.78 (64 bit), Firefox 63.0.3 (64 bit)
 - Sparrow Version: 8.0.19

**Additional context (Error Messages, etc.)**

This problem is caused by the function **triggerUi** (in **app/scripts/background.js**) being called multiple times on batch execute.

<img width="632" alt="Sparrow Broken" src="https://user-images.githubusercontent.com/14117763/105658078-c730ce00-5e93-11eb-9ca3-82dca245cc96.png">

Although the function checks whether a window is already open, the window is only considered "open" once the async function to open it (inside) is awaited.

So if **triggerUi** is called several times at once (before any windows are considered open), it will open them all.

<img width="649" alt="Sparrow Fixed" src="https://user-images.githubusercontent.com/14117763/105658185-02cb9800-5e94-11eb-9106-81f86f8ba243.png">

This problem can be solved by adding a top level variable called **uiIsTriggering** to **background.js**. When **triggerUi** runs, if that variable is true, end the function call with **return;** if it's false, set it to true, then proceed to "try" opening the window. Then, in the try's "finally", set that variable back to false.

**Comment by jyap808** [comment]
Hmm. I thought it was a display issue but this also replicates it.

```
(async () => {
  const account = (await window.ethereum.enable())[0];
  await wait(3000); // wait for window to close
  const web3 = new Web3(window.ethereum);
  const batch = new web3.BatchRequest();
  const transaction1 = web3.eth.sendTransaction.request(
    { from: account, to: account, value: 0, data: "1" },
  );
  const transaction2 = web3.eth.sendTransaction.request(
    { from: account, to: account, value: 0, data: "2" },
  );
  const transaction3 = web3.eth.sendTransaction.request(
    { from: account, to: account, value: 0, data: "3" },
  );
  batch.add(transaction1);
  batch.add(transaction2);
  batch.add(transaction3);
  batch.execute();
})();
```
